version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml

  auth-service:
    build:
      context: ./auth 
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8000
    ports:
      - "8000:8000"
